### ISSUE TITLE
Error reading point and point colours from LAS file

### ISSUE THREAD

**Issue by dispiste** [jblindsay/whitebox-geospatial-analysis-tools#10]
I am using LASReader class to programatically read LAS files from a Java program.
When using getPointRecord(int i) and then getPointRecordColours(int i) to read from the same record, a null value is got as Colour result.

The reason is that getPointRecord(int i) calls to readPointRecords() and initializes startingPoint and endPoint. Then, the next call to getPointRecordColours(int i) checks  startingPoint and endPoint and thinks that the colours are already buffered, so they are actually never read.

**Comment by jblindsay** [comment]
I've just uploaded a fix to the LASReader class that should fix the issue with reading point colour data. I must admit that I've never had a sample of LAS data containing colour data so it is difficult for me to test the fix. Please let me know if there are any further issues. Otherwise I will mark as closed.

**Comment by dispiste** [comment]
Thanks, it seems to be working properly. Note that you can get some LAS samples here:
ftp://ftp.geo.euskadi.net/lidar/LIDAR_2012_ETRS89/LAS/089/

**Comment by jblindsay** [comment]
Thanks for confirming that the fix worked, for providing the links to the data samples, and for taking the time to report the error in the first place. It's certainly appreciated.
