### ISSUE TITLE
Support RPC for integration with 3rd party packages

### ISSUE THREAD

**Issue by rigelrozanski** [jblindsay/whitebox-geospatial-analysis-tools#27]
Worth a discussion, this would allow other non-java programs to remotely call GAT functionality without booting up the whole system and using an API. Integral for integrating GAT into a wider process train that is not exclusively GIS. 

http://stackoverflow.com/questions/9472376/rpc-framework-for-java

**Comment by jblindsay** [comment]
Actually, you will notice that in the latest release of Whitebox (3.4.0), I have included 'Native Plugins'. The plan is to develop most, if not all, new plugin tools using native languages and as separate executables. One of the major rationale for this change is that I know many people would like to be able to call on Whitebox functionality without loading up the user-interface, as you point out. Another plan for the project is to eventually get off of the Java platform. This is a two-step process. First, I plan on moving all of the Whitebox tools over to natively compiled languages and either individual executables or a library of plugin tools. The second stage of this process will involve the eventual redevelopment of the Whitebox user interface in a non-Java alternative. This is a very significant undertaking and this is the reason for the two-stage approach.

**Comment by rigelrozanski** [comment]
wow, yes big process (exciting too). Which languages are you looking at redeveloping in? I've been having a great time coding in golang recently (my plug for go hehe).

**Comment by jblindsay** [comment]
Knowing that this is a big decision, I have spent quite a bit of time evaluating several of the more modern natively compiled languages including Go, D, Rust, Nim, and Crystal. All of these languages have advantages and disadvantages. Go is fantastic and I've developed the GoSpatial library using it, which is actually what provides the new Export GeoTiff tool in 3.4.0. Go also have a wonderful ability to cross-compile to other platforms, which makes the deployment of Whitebox easier. D is a very nice language but I worry about it's long-term vision for various reasons. Rust is the only language on the list that does not use garbage collection (automated memory management) which has serious advantages for performance and in particular it's usefulness for communicating with other languages (e.g. Python). The only disadvantage of Rust is that it is a really tough language to learn (not to bad once you have though), which makes the potential for attracting other developers to the project a bit harder. I have developed all of the other tools in the NativePlugins folder using Rust and have found it to be great. I like both Nim and Crystal a lot but they are both pre-1.0 and that is difficult. Both languages are so easy to learn (and in the case of Nim the syntax is so similar to Python) that it would be great for attracting developers to the project. I believe when Crystal releases 1.0 later this year, it may take a lot of Go's current users because it is a far more advanced language, while retaining all the ease of Go, and with the added bonus of greater performance. Crystal has a very easy Ruby-like syntax. 

Ultimately though, I don't think that there is any need to use one and only one language for this task. The only issue is that there needs to be infrastructure in place to write geospatial analysis tools. For example, I need to develop libraries for reading and writing raster, vector and LiDAR data formats. Right now, I have partial abilities (LiDAR and raster) in all five of the above languages. The Rust geospatial I/O capabilities are so far the furthest along though.

**Comment by rigelrozanski** [comment]
Wow, Thanks for turning me on to crystal, looks great, can't wait until it has reached further development. Also I will check out rust based on your comments. With regards on go's verboseness, you should never need to cut and paste code, for error tracking I'd suggest using function variables and tracing https://play.golang.org/p/vRFiDCpiX2

``` golang 
package main
import (
	"errors"
)
func main() {
	checkError := func(err error) {
		if err != nil {
			panic(err.Error())
		}
	}
	//do something normal
	checkError(nil)
	//do something bad
	checkError(errors.New("foo error"))
}
```
I agree that you do not need a single programming language, however it would be useful to allow for multiple programming languages to call any of the GIS capabilities of whitebox without needing to program a RPC for each programming lang which includes GIS functions you want to utilize, aka only need to RPC to central execution space where whitebox can then call all other languages... I believe this space already exists in whitebox, just without a java rpc.

**Comment by rigelrozanski** [comment]
Also checkout errors with stack trace: https://github.com/pkg/errors

**Comment by jblindsay** [comment]
Significant progress has been made in this area with the development of the new [WhiteboxTools](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/tree/master/whitebox_tools) library. I have currently ported over half of Whitebox GAT's tools to this new Rust-based library. Because these tools are native-code, they are easily callable from Python and other scripting languages from outside of the Whitebox GAT user-interface. As such, I'm marking this issue as closed. Feel free to re-open it if there are further unaddressed aspects.
