### ISSUE TITLE
[bug report] whitebox_tools BreachDepressions algorithm

### ISSUE THREAD

**Issue by anczik** [jblindsay/whitebox-geospatial-analysis-tools#34]
Dear Prof. Lindsay,
I just discovered whitebox_tools and would like to use it to automate processing of DEM data. But it seems that I found a bug in BreachDepressions tool. When I run Breach Depressions algorithm from Whitebox GAT GUI it works perfectly, however, when I run it from command line (whitebox_tools) the resulting raster is odd (invalid?).
I attach screens.
![oryg_dem](https://user-images.githubusercontent.com/32929845/31783742-a81df4b6-b4ff-11e7-82db-93a3d0c425c6.png)
![dem_breachdepressions_whiteboxgat](https://user-images.githubusercontent.com/32929845/31783749-ac7f6e7c-b4ff-11e7-91eb-266a2da74d4d.png)
![dem_breachdepressions_whitebox_tools](https://user-images.githubusercontent.com/32929845/31783771-baf3c6ba-b4ff-11e7-8613-794df575fed0.png)
![dem_breachdepressions_whitebox_tools_blackwhite](https://user-images.githubusercontent.com/32929845/31783776-be632a02-b4ff-11e7-9652-92b11ef036ab.png)

I would appreciate any help, as breaching algorithm is the one I was looking for.

**Comment by jblindsay** [comment]
Hello,

First, the current version of Whitebox GAT does not use **WhiteboxTools** in its backend. Future versions will start to call these Rust-based tools, but the **WhiteboxTools** library is still under development and testing. That means that the Breach Depressions tool in Whitebox GAT is not the same as the Breach Depression tool in **WhiteboxTools**. 

Next, can I ask for details on the script that you are using to call the **WhiteboxTools** BreachDepressions tool? What are the parameters that you are sending to the tool? I have done extensive testing on the BreachDepressions tool and have never come across anything that looks like the situation that you have described above. In particular, the third image does not look like a DEM at all. How was the fourth image created? It looks to be a D8 flow accumulation raster, but was it derived from the third image? It's unclear from the description above.

**Comment by anczik** [comment]
Hello,
Thank you for your quick response. 
It turned out that the issue was an input format of a DEM. 
I run this command:
_whitebox_tools --wd="C:\xxx\auto_proc" -r=BreachDepressions --dem=dem.sgrd -o=dem_BD.sgrd_

Now I've changed input DEM to DEP format and it works as it should. This is an output:
![dem_breachdepressions_whitebox_tools_dep](https://user-images.githubusercontent.com/32929845/31816803-f7fcfb02-b591-11e7-8173-6af786a81ea2.png)

The third and fourth pictures are the same raster. They are just displayed with different colour palettes. Yes, I admit that it looks like flow accumulation raster... It seems that there is a problem with input format, but I am aware that this tool is under development.

I know that WhiteboxTools is written from scratch. And I appreciate your awesome work. However, I've got a question. The BreachDepressions algorithm in WhiteboxTools is equivalent to the **Fast** version in Whitebox GAT, and as you can see it doesn't breach through the bridge. I am very interested in a basic version of this algorithm (co called **optimized**), as it lets water to flow through bridge. I know that it is to be ported and my question is when it will be available.

**Comment by jblindsay** [comment]
The WhiteboxTools BreachDepressions tool is actually the same as the GoSpatial BreachDepressions tool, rather than the Whitebox GAT Breach Depressions (Fast) tool. This follows the algorithm of:

Lindsay JB. 2016. Efficient hybrid breaching-filling sink removal methods for flow path enforcement in digital elevation models. Hydrological Processes, 30(6): 846–857. DOI: 10.1002/hyp.10648

The optimized algorithm is actually based on:

Lindsay J, Dhun K. 2015. Modelling surface drainage patterns in altered landscapes using LiDAR. International Journal of Geographical Information Science, 29: 1-15. DOI: 10.1080/13658816.2014.975715

And I have not yet found the time to re-implement this algorithm in WhiteboxTools. Eventually I'll get to it, but in many cases the Lindsay (2016) algorithm will work just as well while also performing far more efficiently. 

It seems that this issue was a data input issue and so I am marking it as closed now. If you have further questions, please email me and I'll see if I can help.

**Comment by anczik** [comment]
I will take a look at provided articles.
Once again thank you and can't wait for futher development.

**Comment by jpmill09** [comment]
Hello Professor Lindsay,

First of all, thank you for all of the important work you've done with Whitebox GAT and WhiteboxTools - I use them frequently and find them of immense value. 

My office/company, like many others, has typically relied on filling sinks. We've come to realize that breaching could be a superior option however and are currently evaluating a number of potential options, including both Whitebox GAT and WhiteboxTools. Ideally we would like to use WhiteboxTools so that we can incorporate it into scripts for automation.

As an initial analysis, we've compared results from ArcHydro, GRASS, an in-house tool, a USGS selective breach [tool](https://pubs.usgs.gov/sir/2010/5059/pdf/SIR2010_5059.pdf), and Whitebox GAT & WhiteboxTools. The results displayed by @anczik once they correctly used a .dep file is not an anomaly in our experience. Below is an example of our results. The optimized breach (Lindsay, 2015) is in pink, blue is the breach depressions (fast) in Whitebox GAT, green is GRASS, and orange is our in-house tool (similar to burning). Your optimized tool is the only one to correctly capture the stream location for crossing beneath the road embankment. For reference this is a roughly 2 square mile drainage area in mountainous West Virginia. 

![streamline study example](https://user-images.githubusercontent.com/35961262/53109408-cf916900-3506-11e9-8037-b79650b33add.png)

**Comment by RitikaPrasai** [comment]
I am trying to use the same algorithm in my geotiff file format. Could you all suggest me if it is possible to use geotiff format in White Box GAT?
