### ISSUE TITLE
[whitebox tools] Confusing tool parameters in FD8FlowAccumulation

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-geospatial-analysis-tools#46]
Looking at the `FD8FlowAccumulation` tool parameters there is an `--out_type` parameter which accepts one of the predefined options 'cells', 'sca', and 'ca' (taken from the parameter name). However, in the options list we have full options, not short:
```"parameter_type":{"OptionList":["Cells","Specific Contributing Area","Catchment Area"]}```

**Comment by jblindsay** [comment]
Yes, this was certainly confusing. In fact, the tool will accept either the shorthand or longhand versions of the output type. For parameter specifications, used in GUIs, the longhand form makes sense but when the tool is run by the command line, it's far easier to write --out_type=sca then --out_type="specific catchment area". Nonetheless, I do agree that I need to decide on one form of the parameter options and stick with it. I've decided to go with the longhand form for parameter specification (although notice that the tool will still function with the shorthand form). This is fixed with commit: [1fd3b790b1552a5bc8870dbade508b2fca26248a](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/commit/1fd3b790b1552a5bc8870dbade508b2fca26248a) which affects both the D8FlowAccumulation and FD8FlowAccumulation tools.

**Comment by alexbruy** [comment]
Thanks for the explanation! I agree that long form is much better from the UX point of view, especially if tools called with the help of some GUI, e.g. wb_runner, QGIS or something else.
