### ISSUE TITLE
NewRasterFromBase on Windows: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by AlisterH** [jblindsay/whitebox-geospatial-analysis-tools#55]
Hi, see below.
Is this a bug, or am I just not giving it the right input data?
I note that the backtrace doesn't look very useful - is that normal?

````
C:\Program Files\QGIS 3.4\bin>whitebox_tools.exe --version
whitebox-tools v0.11.0 by Dr. John B. Lindsay (c) 2017-2018

C:\Program Files\QGIS 3.4\bin> set RUST_BACKTRACE=1

C:\Program Files\QGIS 3.4\bin>whitebox_tools.exe --run=NewRasterFromBase --input="C:/Users/alistair/AppData/Local/Temp/processing_7485b4fd49014ca7bfae36b6560e507c/2369d150378d4c688bb8dd4281e6e477/OUTPUT.tif" --value=1.32 --output="C:/Users/alistair/AppData/Local/Temp/processing_7485b4fd49014ca7bfae36b6560e507c/2369d150378d4c688bb8dd4281e6e477/try.tif" -v
********************************
* Welcome to NewRasterFromBase *
********************************
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:345:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: BaseThreadInitThunk
  22: RtlUserThreadStart

**Comment by jblindsay** [comment]
Hello @AlisterH. First, this issue is related to the WhiteboxTools project (repo: https://github.com/jblindsay/whitebox-tools) and not the Whitebox GAT GIS. These are two different projects and repositories. This issue should really be reported in the other GitHub repo and so I will be closing it down after this comment. Secondly, it is strange to me that the printout that you agve above does not have the `data_type` flag. I see that you are running WhiteboxTools through the QGIS plugin. Which version of the plugin are you using? I see that you are running v0.11 of WhiteboxTools, which is the latest public release version, but I know that the QGIS plugin recently updated, I think to v0.8. You should try updating that and running it again. I have just run the NewRasterFromBase tool on my machine (a Mac) and I did not encounter any errors. 

It might also be your GeoTIFF. Not all flavours of GeoTIFF are supported by the WhiteboxTools library. For example, we don't support all types of data compression.
