### ISSUE TITLE
Shapefile geometry type support

### ISSUE THREAD

**Issue by lahm3d** [jblindsay/whitebox-geospatial-analysis-tools#58]
Not sure, if this is an issue or user error, but I am trying to use WBT clip tool to extract streams (polyline) inside a watershed (polygon) and I get the following error:

```
Reading data...
thread 'main' panicked at 'Unrecognized ShapeType', src\vector\shapefile\geometry.rs:483:18
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I checked the geometry types of my datasets: watershed = 'Polygon' and streams = 'LineString', however, after looking through `geometry.rs` I see no reference to `LineString`. Is there something I'm missing here?

**Comment by jblindsay** [comment]
@lahm3d It sounds like this is an issue that belongs in the [whitebox-tools](https://github.com/jblindsay/whitebox-tools) repository rather than Whitebox Geospatial Analysis Tools. I am therefore going to close it here but feel free to re-open it in the appropriate Github repository. Anyhow, I'm not sure how you generated your streams layer but there is no `LineString` ShapeType in the [Shapefile specs](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf). There is a `PolyLine`, a `PolyLineZ`, and a `PolyLineM`, all of which are supported by WhiteboxTools. What software was the file created with?

**Comment by lahm3d** [comment]
So sorry! I had both repos open in different tabs. I will reopen and update how the file was created under correct repo.
